"""Patch generator — auto-generates and submits PRs for safe version bumps.

Uses the GitHub Contents API to create branches and commit files remotely,
avoiding the need for authenticated ``git push``.
All temp directory operations are wrapped in try/finally with cleanup
to prevent disk leaks.
"""

from __future__ import annotations

import asyncio
import base64
import logging
import re
import shutil
import tempfile
import uuid
from typing import TYPE_CHECKING

from src.security import SAFE_BRANCH_RE

if TYPE_CHECKING:
    from pathlib import Path

    from src.github.client import GitHubClient
    from src.intelligence.database import IntelligenceDB
    from src.models.patrol import DependencyFinding

logger = logging.getLogger(__name__)

_TEST_TIMEOUT = 300  # seconds
_PR_BODY_TEMPLATE = """\
## Automated Security Patch

**Package**: `{package_name}`
**Vulnerability**: {cve_id}
**Current version**: `{old_version}`
**Patched version**: `{new_version}`

This is an automated security patch generated by SaltaX Patrol.
Manual review is recommended before merging.
"""


def _sanitize_branch_name(raw: str) -> str:
    """Sanitize a branch name for git ref safety.

    Replaces characters outside ``[A-Za-z0-9._/-]`` with ``-``,
    collapses multiple dashes, and truncates to 255 chars.
    """
    sanitized = re.sub(r"[^A-Za-z0-9._/-]", "-", raw)
    sanitized = re.sub(r"-{2,}", "-", sanitized)
    return sanitized[:255]


class PatchGenerator:
    """Generates version-bump PRs for dependency vulnerabilities."""

    def __init__(
        self,
        github_client: GitHubClient,
        intel_db: IntelligenceDB,
    ) -> None:
        self._github = github_client
        self._db = intel_db

    async def generate_and_submit(
        self,
        repo: str,
        finding: DependencyFinding,
        installation_id: int,
        source_repo_path: Path | None = None,
    ) -> int | None:
        """Attempt to patch a dependency and open a PR.

        Parameters
        ----------
        source_repo_path:
            Path to an already-cloned repository. When provided, a fast local
            ``shutil.copytree`` is used instead of a fresh ``git clone``.

        Returns the PR number on success, or ``None`` if patching is not
        possible (no fixed version, test failure, clone failure).
        """
        if finding.fixed_version is None:
            logger.info(
                "No fixed version for %s, skipping patch",
                finding.package_name,
            )
            return None

        tmp_dir = tempfile.mkdtemp(prefix="patrol-patch-")
        try:
            return await self._do_patch(
                repo, finding, installation_id, tmp_dir, source_repo_path,
            )
        except Exception:
            logger.exception(
                "Patch generation failed for %s in %s",
                finding.package_name, repo,
            )
            return None
        finally:
            shutil.rmtree(tmp_dir, ignore_errors=True)

    async def _do_patch(
        self,
        repo: str,
        finding: DependencyFinding,
        installation_id: int,
        tmp_dir: str,
        source_repo_path: Path | None = None,
    ) -> int | None:
        from pathlib import Path as _Path  # noqa: PLC0415

        target = _Path(tmp_dir) / "repo"

        # Use local copy if available (Fix 7), otherwise clone
        if source_repo_path is not None:
            shutil.copytree(source_repo_path, target)
        else:
            clone_url = f"https://github.com/{repo}.git"
            await self._github.clone_repo(clone_url, target, "main")

        # Apply version bump
        bumped = self._apply_bump(target, finding)
        if not bumped:
            logger.info("Could not apply bump for %s", finding.package_name)
            return None

        # Run tests (best-effort)
        tests_pass = await self._run_tests(target, finding.language)
        if not tests_pass:
            logger.info(
                "Tests failed after bumping %s, skipping PR",
                finding.package_name,
            )
            return None

        # Build branch name and validate
        branch_name = _sanitize_branch_name(
            f"patrol/bump-{finding.package_name}-{finding.fixed_version}",
        )
        if not SAFE_BRANCH_RE.match(branch_name):
            logger.error("Branch name failed safety check: %s", branch_name)
            return None

        # Create branch via GitHub API (Fix 1)
        base_sha = await self._github.get_ref(repo, installation_id, "heads/main")
        await self._github.create_ref(
            repo, installation_id,
            ref=f"refs/heads/{branch_name}",
            sha=base_sha,
        )

        # Identify and commit changed files via GitHub Contents API
        changed_files = self._find_changed_files(target, finding)
        for file_path in changed_files:
            full_path = target / file_path
            if not full_path.exists():
                continue
            content_bytes = full_path.read_bytes()
            content_b64 = base64.b64encode(content_bytes).decode()

            # Get the file's blob SHA on the base branch for update
            file_sha = await self._get_file_sha(
                repo, installation_id, file_path,
            )
            await self._github.create_or_update_contents(
                repo, installation_id,
                path=file_path,
                message=f"security: bump {finding.package_name} to {finding.fixed_version}",
                content_b64=content_b64,
                branch=branch_name,
                sha=file_sha,
            )

        # Open PR
        cve_label = finding.cve_id or finding.package_name
        pr_body = _PR_BODY_TEMPLATE.format(
            package_name=finding.package_name,
            cve_id=cve_label,
            old_version=finding.current_version,
            new_version=finding.fixed_version,
        )

        pr_data = await self._github.create_pull_request(
            repo,
            installation_id,
            title=f"security: bump {finding.package_name} to {finding.fixed_version}",
            body=pr_body,
            head=branch_name,
            base="main",
        )
        pr_number = int(pr_data["number"])

        # Record in DB
        patch_id = uuid.uuid4().hex[:16]
        await self._db.record_patrol_patch(
            patch_id=patch_id,
            repo=repo,
            pr_number=pr_number,
            cve_id=finding.cve_id,
            package_name=finding.package_name,
            old_version=finding.current_version,
            new_version=finding.fixed_version,
            status="submitted",
        )

        logger.info(
            "Created patch PR #%d for %s in %s",
            pr_number, finding.package_name, repo,
        )
        return pr_number

    async def _get_file_sha(
        self, repo: str, installation_id: int, path: str,
    ) -> str | None:
        """Get the blob SHA for an existing file, or ``None`` for new files."""
        try:
            response = await self._github._request(
                "GET",
                f"/repos/{repo}/contents/{path}",
                installation_id=installation_id,
            )
            data = response.json()
            return data.get("sha")
        except Exception:
            return None

    @staticmethod
    def _find_changed_files(repo_path: Path, finding: DependencyFinding) -> list[str]:
        """Return the manifest file path(s) that the bump would have modified."""
        candidates: list[str] = []
        if finding.language == "python":
            if (repo_path / "requirements.txt").exists():
                candidates.append("requirements.txt")
            if (repo_path / "pyproject.toml").exists():
                candidates.append("pyproject.toml")
        elif finding.language == "node":
            if (repo_path / "package.json").exists():
                candidates.append("package.json")
        elif finding.language == "rust":
            if (repo_path / "Cargo.toml").exists():
                candidates.append("Cargo.toml")
        return candidates

    @staticmethod
    def _apply_bump(repo_path: Path, finding: DependencyFinding) -> bool:
        """Apply a version bump in the appropriate manifest file.

        Returns True if a change was made, False otherwise.
        """
        if finding.fixed_version is None:
            return False

        if finding.language == "python":
            return _bump_python(repo_path, finding)
        if finding.language == "node":
            return _bump_node(repo_path, finding)
        if finding.language == "rust":
            return _bump_rust(repo_path, finding)
        return False

    @staticmethod
    async def _run_tests(repo_path: Path, language: str) -> bool:
        """Run basic tests in the repo. Returns True if they pass."""
        import subprocess  # noqa: PLC0415

        if language == "python":
            cmd = ["python", "-m", "pytest", "--tb=no", "-q"]
        elif language == "node":
            cmd = ["npm", "test"]
        elif language == "rust":
            cmd = ["cargo", "test"]
        else:
            return True  # no tests to run, assume pass

        if shutil.which(cmd[0]) is None:
            return True  # tool not available, skip tests

        proc = await asyncio.create_subprocess_exec(
            *cmd,
            cwd=str(repo_path),
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        try:
            await asyncio.wait_for(proc.wait(), timeout=_TEST_TIMEOUT)
        except TimeoutError:
            from contextlib import suppress  # noqa: PLC0415

            with suppress(ProcessLookupError):
                proc.kill()
            with suppress(BaseException):
                await proc.wait()
            return False

        return proc.returncode == 0


# ── Ecosystem-specific bump helpers ───────────────────────────────────────────


def _bump_python(repo_path: Path, finding: DependencyFinding) -> bool:
    """Bump a package version in requirements.txt or pyproject.toml."""
    # Try requirements.txt first
    req_file = repo_path / "requirements.txt"
    if req_file.exists():
        content = req_file.read_text()
        old_spec = f"{finding.package_name}=={finding.current_version}"
        new_spec = f"{finding.package_name}=={finding.fixed_version}"
        if old_spec in content:
            req_file.write_text(content.replace(old_spec, new_spec, 1))
            return True
        # Try without pinned version
        if finding.package_name in content:
            old_spec = finding.package_name
            new_spec = f"{finding.package_name}>={finding.fixed_version}"
            req_file.write_text(content.replace(old_spec, new_spec, 1))
            return True

    # Try pyproject.toml (Fix 8)
    pyproject_file = repo_path / "pyproject.toml"
    if pyproject_file.exists():
        return _bump_pyproject_toml(pyproject_file, finding)

    return False


def _bump_pyproject_toml(pyproject_file: Path, finding: DependencyFinding) -> bool:
    """Bump a package version in pyproject.toml [project.dependencies]."""
    import tomllib  # noqa: PLC0415

    content = pyproject_file.read_text()
    try:
        tomllib.loads(content)  # validate TOML
    except tomllib.TOMLDecodeError:
        return False

    # Text-based replacement in [project.dependencies] or [tool.poetry.dependencies]
    # Handles patterns like: "package_name==1.0.0", "package_name>=1.0.0", "package_name~=1.0.0"
    pkg = re.escape(finding.package_name)
    old_ver = re.escape(finding.current_version)
    pattern = re.compile(
        rf'("{pkg}\s*(?:[><=~!]+\s*)?){old_ver}(")',
        re.IGNORECASE,
    )
    new_content, count = pattern.subn(rf'\g<1>{finding.fixed_version}\2', content, count=1)
    if count > 0:
        pyproject_file.write_text(new_content)
        return True
    return False


def _bump_node(repo_path: Path, finding: DependencyFinding) -> bool:
    """Bump a package version in package.json."""
    import json  # noqa: PLC0415

    pkg_file = repo_path / "package.json"
    if not pkg_file.exists():
        return False

    data = json.loads(pkg_file.read_text())
    changed = False
    for section in ("dependencies", "devDependencies"):
        deps = data.get(section, {})
        if finding.package_name in deps:
            deps[finding.package_name] = f"^{finding.fixed_version}"
            changed = True

    if changed:
        pkg_file.write_text(json.dumps(data, indent=2) + "\n")
    return changed


def _bump_rust(repo_path: Path, finding: DependencyFinding) -> bool:
    """Bump a package version in Cargo.toml."""
    cargo_file = repo_path / "Cargo.toml"
    if not cargo_file.exists():
        return False

    content = cargo_file.read_text()
    # Simple string replacement for exact version pins
    old_spec = f'"{finding.current_version}"'
    new_spec = f'"{finding.fixed_version}"'
    if old_spec in content:
        cargo_file.write_text(content.replace(old_spec, new_spec, 1))
        return True
    return False
